# Funding options for Expo Upgrade Wizard

github: [expo-upgrade-wizard]
# patreon: expo-upgrade-wizard
# open_collective: expo-upgrade-wizard
# ko_fi: expo-upgrade-wizard
# custom: ['https://expo-upgrade-wizard.dev/sponsor']
